name: stock_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  intl: ^0.18.0  
  provider: ^6.1.2
  rxdart: ^0.28.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0


flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
  colors:
    inputs:
      - assets/colors/colors.xml
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Manrope-Regular
      fonts:
        - asset: fonts/Manrope-Regular.ttf
    - family: Manrope-Medium
      fonts:
        - asset: fonts/Manrope-Medium.ttf
    - family: Manrope-SemiBold
      fonts:
        - asset: fonts/Manrope-SemiBold.ttf
    - family: Manrope-Light
      fonts:
        - asset: fonts/Manrope-Light.ttf
    - family: Manrope-ExtraLight
      fonts:
        - asset: fonts/Manrope-ExtraLight.ttf
    - family: Manrope-Bold
      fonts:
        - asset: fonts/Manrope-Bold.ttf
    - family: Manrope-ExtraBold
      fonts:
        - asset: fonts/Manrope-ExtraBold.ttf

    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope-ExtraBold.ttf
          weight: 800

